### ISSUE TITLE
Request for newer version (due to push notification issue)

### ISSUE THREAD

**Issue by Jayky-II** [syncloud/rocketchat#3]
Is there a plan for an upgrade of rocketchat to a newer version that supports push notifications (of course when connected to cloud.rocket.chat)?

**Comment by cyberb** [comment]
Here is the issue and a workaround: https://github.com/syncloud/platform/issues/555

**Comment by Jayky-II** [comment]
Hi,

thanks for the link. I use an OHC1 from Syncloud and it has an arm32 architecture. So the provided link wasn't a solution for me (or I just didn't understand the hint how to solve it on arm32).

Just in case, if there is an solution for servers with arm32 architecture, please post that link, too.

**Comment by cyberb** [comment]
Unfortunately I am not aware of any fix to produce a required version of Mongo database for arm32 and that means RocketChat cannot be updated on this architecture.
I have updated the original issue with more details.
